[package]
name = "timestone_window"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.54", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_UI_HiDpi", "Win32_UI_WindowsAndMessaging"] }
